name: BB-Import
id: bb-import
version: 0.1.0
build-date: 20230718-0001
synopsis: Bash-Bits Import Module
description: |
	The Bash-Bits Import Module - The most important and magical part of Bash-Bits!

	BB-Import is obviously a utility which imports external code / libraries into your Bash scripts - but it's HOW BB-Import does it which is special!  Best of all, it's not limited to working with only Bash-Bits-compatible code - you can use BB-Import in any of 4 different ways to import ANY script from ANY server on the planet directly into YOUR code!

	And that's not even the best bit!  Once BB-Import has downloaded that project / repo / file to your local machine, it is cached there FOREVER - which means, rather than downloading it from the Internet every time you want to use your software, BB-Import will download it ONCE, and from then-on will use its locally-cached version unless it's told to go and fetch a new version.

	AND THE NEXT VERSION WILL EVEN KEEP TRACK OF THE LATEST VERSIONS OF EACH AND EVERY PACKAGE IT MANAGES!!

	That will mean that you're always GUARANTEED to be using the very latest version of that code that is available!

	Please ensure that you read at least the repository's README file to better understand this module.
category: Development
author: Ragdata<ragdata@ragdata.dev>
maintainer: Ragdata<ragdata@ragdata.dev>
license: MIT
homepage: https://github.com/bash-bits/bb-import
repository: https://github.com/bash-bits/bb-import
